server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
